name: "habit_to_do_some_level_up"
description: "Experience-based Todo and Habits App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  intl: ^0.20.2
  fl_chart: ^1.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
